package online.getschool.cobranca.integracao.banco.inter.dto

enum class TipoDescontoInterEnum {
    NAOTEMDESCONTO,
    VALORFIXODATAINFORMADA,
    PERCENTUALDATAINFORMADA,
    VALORANTECIPACAODIACORRIDO,
    VALORANTECIPACAODIAUTIL,
    PERCENTUALVALORNOMINALDIACORRIDO,
    PERCENTUALVALORNOMINALDIAUTIL
}