package online.getschool.cobranca.dominio.boleto.dto

enum class TipoDescontoEnum {
    VALOR_FIXO_DATA_INFORMADA,
    PERCENTUAL_DATA_INFORMADA,
    VALOR_ANTECIPACAO_DIA_CORRIDO,
    VALOR_ANTECIPACAO_DIA_UTIL,
    PERCENTUAL_VALOR_NOMINAL_DIA_CORRIDO,
    PERCENTUAL_VALOR_NOMINAL_DIA_UTIL
}